### ISSUE TITLE
Index for WET files?

### ISSUE THREAD

**Issue by azzurolilc** [commoncrawl/commoncrawl#11]
Hi, hope I am posting this questions in the right place... 

I found .WARC format domain index at http://index.commoncrawl.org/CC-MAIN-2016-18//
I wonder if there is any indexing for .WET format files? 

If not, is there anyway I could convert the WARC object address to WET object address?
For example, if I have:
s3://commoncrawl/crawl-data/CC-MAIN-2016-18/segments/1461860125175.9/warc/CC-MAIN-20160428161525-00221-ip-10-239-7-51.ec2.internal.warc.gz 
What would be the corresponding .WET file?

Thx...

**Comment by sebastian-nagel** [comment]
Hi,
the better place for questions would be the Common Crawl user group at
  https://groups.google.com/forum/#!forum/common-crawl
You'll probably get a quick answer from users in various time zones.

Unfortunately, we do not provide an index to WET files. It's easy to achieve the location of a WET (or WAT) file given a WARC file:
- replace `/warc/` by `/wet/`in the path
- add `.wet` before the suffix `.gz`
```
s3://commoncrawl/crawl-data/CC-MAIN-2016-18/segments/1461860125175.9/warc/CC-MAIN-20160428161525-00221-ip-10-239-7-51.ec2.internal.warc.gz
s3://commoncrawl/crawl-data/CC-MAIN-2016-18/segments/1461860125175.9/wet/CC-MAIN-20160428161525-00221-ip-10-239-7-51.ec2.internal.warc.wet.gz
```
The Common Crawl index also provides offsets into the WARC file, which could be used to estimate the offsets in the WET file.

**Comment by sebastian-nagel** [comment]
Closing this issue as it does not belong to this repository. Thanks!

**Comment by allexg** [comment]
sorry, but I saw your comment @sebastian-nagel :  'The Common Crawl index also provides offsets into the WARC file, which could be used to estimate the offsets in the WET file.' Do you know how this estimation can be done? I wish to avoid downloading the whole WET file, only because I need just one record. And I have to do this operation many times. Thanks a lot!

**Comment by imrulhuda** [comment]
The Common Crawl index also provides offsets into the WARC file, which could be used to estimate the offsets in the WET file.

Can you please briefly explain this. How do I estimate the offset?

**Comment by yickminglee** [comment]
@sebastian-nagel Can you please briefly explain this. How do I estimate the offset? Thank you. Ming

**Comment by temurchichua** [comment]
Did you find the answer?

In the CDX  file, each WARC has its offset, and the length is written next to the URL, Can I find the same information about the WET files?
