### ISSUE TITLE
Broken link on main site

### ISSUE THREAD

**Issue by adamchainz** [commoncrawl/commoncrawl#12]
I can't find a repository for the main site, but I thought I'd report it

The link "A distributed system for mining Common Crawl using SQS, AWS-EC2 and S3 by Akshay Bhat" on https://commoncrawl.org/the-data/examples/ is broken. From googling it looks like it should point to https://github.com/jrs026/CommonCrawlMiner maybe

**Comment by sebastian-nagel** [comment]
Thanks for reporting that. We hope to overhaul the examples page soon and we plan to remove all examples with dead links to code. Btw., this [repo](https://github.com/gfjreg/CommonCrawl) looks like a fork of @AKSHAYUBHAT's example.

**Comment by sebastian-nagel** [comment]
Closing this issue as it does not belong to this repository. Thanks!
